#!/bin/bash

wx_location=
wx_do_conditions=0
wx_do_forecast=0
wx_do_hourly=0
wx_do_forecast_long=0
wx_do_forecast_short=0
wx_do_temp=0

debug=0

while [ $# -gt 0 ] ; do
  case $1 in
    -g|--debug) debug=1 ;;
    -c)  wx_do_conditions=1 ;;
    -f)  wx_do_forecast=1 ;;
    -fs) wx_do_forecast=1 ; wx_do_forecast_short=1 ;;
    -fl) wx_do_forecast=1 ; wx_do_forecast_long=1 ;;
    -h)  wx_do_hourly=1 ;;
    -t)  wx_do_temp=1 ;;
    *)
      if [ "$wx_location" = "" ] ; then
        wx_location="$1"
      else
        wx_location="${wx_location} $1"
      fi
      ;;
  esac
  shift
done

if [ $((wx_do_conditions+wx_do_forecast+wx_do_hourly+wx_do_temp)) -eq 0 ] ; then
  wx_do_conditions=1
  wx_do_forecast=1
#  wx_do_hourly=1
fi

if [ $debug -ne 0 ] ; then
  exec 3>&2
else
  exec 3>/dev/null
fi

longest()
{
  ll=0
  while read aa ; do
    if [ ${#aa} -gt $ll ] ; then
      ll=${#aa}
    fi
  done
  echo $ll
}

loccache="${HOME}/.wx-loc-cache"
locdata=
locname=
getloc()
{
  echo "getloc $1" >&3
  local cached=0
  if [ -f "$loccache" ] ; then
    locdata=$(jq -rc '. | select(.loc | test("^'"$1"'$"; "i"))' <"$loccache" | head -1)
    if [ "$locdata" ] ; then
      cached=1
      echo "   cached: $1" >&3
      echo "           $locdata" >&3
      echo "$locdata" | jq -c .
    fi
  else
    touch "$loccache"
  fi

  if [ $cached -eq 0 ] ; then
    locdata=$( \
      curl -sG "https://nominatim.openstreetmap.org/search" \
        -H 'User-Agent: wx-script/1.0 (dpr-wx-script@riesz.net)' \
        --data-urlencode "q=$1" \
        --data-urlencode "format=json" \
        --data-urlencode "limit=1" \
        --data-urlencode "countrycodes=us" \
      | jq -c '.[0]'
    )
    echo "$locdata" | jq -c '. += {"loc":"'"$1"'"}' | tee -a "$loccache"
  fi
}

coords()
{
  echo "coords($1)" >&3
  locdata=$(getloc "$1")
  echo "coords() $1 : $locdata" >&3
  IFS='|' read ll locname < <(jq -r '. | "\(.lat),\(.lon)|\(.name)"' <<<"$locdata")
  if [ "$ll" != "" ] ; then
    echo "$ll"
  fi
}

fwb=211.97
cwb=100.00
fwf=32.00
cwf=0.00
temptoF()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    v2=$(echo "1k $fwb $fwf - $cwb $cwf - / $v * 32.00 + p q" | dc | sed "s/\(\.[0-9]\)[0-9]*$/\1/g")
    printf "%s \u00b0F" "$v2"
  fi
}

pahg=0.00029529983
presstoInHg()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    v2=$(echo "1k $v $pahg * p q" | dc | sed "s/\(\.[0-9]\)[0-9]*$/\1/g")
    printf "%s in-Hg" "$v2"
  fi
}

pcttoStr()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    v2=$(sed "s/\.[0-9]*$//g" <<<"$v")
    printf "%s %%" "$v2"
  fi
}

degtoStr()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    printf "%s \u00b0" "$v"
  fi
}

mmin=0.039370079
mmtoIn()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    v2=$(echo "1k $v $mmin * p q" | dc | sed "s/\(\.[0-9]\)[0-9]*$/\1/g")
    printf "%s in" "$v2"
  fi
}

mmi=0.00062137119
mtoMi()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    v2=$(echo "1k $v $mmi * p q" | dc | sed "s/\(\.[0-9]\)[0-9]*$/\1/g")
    printf "%s mi" "$v2"
  fi
}

khmh=0.62137119
kphtoMph()
{
  IFS='|' read v u < <(jq -r '. | "\(.value)|\(.unitCode)"' <<<"$1")
  if [ "$v" = null ] ; then
    echo null
  else
    v2=$(echo "1k $v $khmh * p q" | dc | sed "s/\(\.[0-9]\)[0-9]*$/\1/g")
    printf "%s mph" "$v2"
  fi
}

getwxurl()
{
  ll=$(coords "$1")
  if [ "$ll" = "null,null" -o "$ll" = "" ] ; then return ; fi
  local wxu="https://api.weather.gov/points/$ll"
  echo "getwxurl(): $wxu" >&3
  echo "$wxu"
}

wx_point_data=
getwx_point_data()
{
  local wxurl=$(getwxurl "$1")
  if [ "$wxurl" = "" ] ; then return ; fi
  wx_point_data=$(curl -sfLG "$wxurl" | jq -c .)
}

getwx_conditions()
{
  local stnsurl=$(jq -r '.properties.observationStations' <<<"$wx_point_data")
  echo "getwx_cond($1) stnsurl: $stnsurl" >&3
  local wxdata2=$(curl -sfLG "$stnsurl" )
  echo "getwx_cond($1): wxdata2: ${#wxdata2} bytes" >&3
  if [ "$wxdata2" = "" ] ; then
    echo "Invalid Location: $1" >&2
    return
  fi
  local obsvurl=$(jq -r '.features[0].id' <<<"$wxdata2")/observations/latest
  echo "getwx_cond($1): obsvurl: $obsvurl" >&3
  local obsv=$(curl -sfLG "$obsvurl" | jq .properties)

  local station timestamp temperature dewpoint winddir windspeed windgust \
        baropress seapress visibility maxtemp24 mintemp24 precip3 relhumid \
        windchill heatindex

  IFS='|' read \
    station \
    timestamp \
    temperature \
    dewpoint \
    winddir \
    windspeed \
    windgust \
    baropress \
    seapress \
    visibility \
    maxtemp24 \
    mintemp24 \
    precip3 \
    relhumid \
    windchill \
    heatindex < <(jq -r '. | "\(.stationName)|\(.timestamp)|\(.temperature)|\(.dewpoint)|\(.windDirection)|\(.windSpeed)|\(.windGust)|\(.barometricPressure)|\(.seaLevelPressure)|\(.visibility)|\(.maxTemperatureLast24Hours)|\(.minTemperatureLast24Hours)|\(.precipitationLast3Hours)|\(.relativeHumidity)|\(.windChill)|\(.heatIndex)"' <<<"$obsv")

  timestamp=$(   date --date="$timestamp"   )
  temperature=$( temptoF     "$temperature" )
  dewpoint=$(    temptoF     "$dewpoint"    )
  winddir=$(     degtoStr    "$winddir"     )
  windspeed=$(   kphtoMph    "$windspeed"   )
  windgust=$(    kphtoMph    "$windgust"    )
  baropress=$(   presstoInHg "$baropress"   )
  seapress=$(    presstoInHg "$seapress"    )
  visibility=$(  mtoMi       "$visibility"  )
  maxtemp24=$(   temptoF     "$maxtemp24"   )
  mintemp24=$(   temptoF     "$mintemp24"   )
  precip3=$(     mmtoIn      "$precip3"     )
  relhumid=$(    pcttoStr    "$relhumid"    )
  windchill=$(   temptoF     "$windchill"   )

  printf "** Conditions at: %s\n" "$station"
  printf "**                %s\n" "$timestamp"
  
  (
#    printf "%s|%s\n" "Station:"                  "$station"
#    printf "%s|%s\n" "Time:"                     "$timestamp"
    printf "%s|%s\n" "Temperature:"              "$temperature"
    printf "%s|%s\n" "Dewpoint:"                 "$dewpoint"
    printf "%s|%s\n" "Wind Direction:"           "$winddir"
    printf "%s|%s\n" "Wind Speed:"               "$windspeed"
    printf "%s|%s\n" "Wind Gust:"                "$windgust"
    printf "%s|%s\n" "Barometric Pressure:"      "$baropress"
    printf "%s|%s\n" "Sea Level Pressure:"       "$seapress"
    printf "%s|%s\n" "Visibility:"               "$visibility"
    printf "%s|%s\n" "Max. 24-hour Temperature:" "$maxtemp24"
    printf "%s|%s\n" "Min. 24-hour Temperature:" "$mintemp24"
    printf "%s|%s\n" "3-hour Precipitation:"     "$precip3"
    printf "%s|%s\n" "Relative Humidity:"        "$relhumid"
    printf "%s|%s\n" "Windchill:"                "$windchill"
  ) | egrep -v "\|null$" | column -t -s '|'
}

getwx_forecast()
{
  echo "getwx_forecast()" >&3
  local fcsturl=$(jq -r '.properties.forecast' <<<"$wx_point_data")
  echo "getwx_forecast() fcsturl: $fcsturl" >&3
  local fcstdata=$(curl -sfLG "$fcsturl" | jq .)
  echo "getwx_forecast() fcstdata bytes: ${#fcstdata}" >&3
  zonename=$(jq -r '.properties.name' < <(curl -sfLG "$(jq -r '.properties.forecastZone' <<<"$wx_point_data")"))
  echo "getwx_forecast() zonename: $zonename" >&3
  local -a fcstitems
  IFS=$'\n' fcstitems=( $(jq -c '.properties.periods[]' <<<"$fcstdata") )
  echo "getwx_forecast() fcstitems count: ${#fcstitems[@]}" >&3
  printf "Forecast for %s\n" "$zonename" | fmt -w 72 | sed "s/^/** /g"
  
  namelen=$(jq -r '.name' <<<"${fcstitems[@]}" | longest)
  indentstr=$(printf "%${namelen}s %6s   " " " " ")
  indentlen=${#indentstr}
  fcstwrap=$((72-indentlen))
  for (( ii=0 ; ii<${#fcstitems[@]} ; ii++ ))
  {
    IFS='|' read num name day isdaytime temp tempunit probprecip windsp winddir shfcst lnfcst \
      < <(jq -r '"\(.number)|\(.name)|\(.startTime)|\(.isDaytime)|\(.temperature)|\(.temperatureUnit)|\(.probabilityOfPrecipitation.value)|\(.windSpeed)|\(.windDirection)|\(.shortForecast)|\(.detailedForecast)"' <<<"${fcstitems[$ii]}")
    if [ $wx_do_forecast_short -eq 1 ] ; then
      printf "%-${namelen}s %6s - %s\n" "$name" "$(date --date="$day" +'%-d %b')" "$shfcst"
      printf "%-${namelen}s %6s   temp: %3d\u00b0%s - precip: %3d%% - wind: %-2s %14s\n" \
        " " " " \
        "$temp" "$tempunit" \
        "$probprecip" \
        "$winddir" "$windsp"
    elif [ $wx_do_forecast_long -eq 1 ] ; then
      fcststr=$(fmt -w $fcstwrap <<<"$lnfcst")
      fcststr="${fcststr//$'\n'/$'\n'$indentstr}"
      printf "%-${namelen}s %6s - %s\n" "$name" "$(date --date="$day" +'%-d %b')" "$fcststr"
    else
      printf "%-${namelen}s %6s   temp: %3d\u00b0%s - precip: %3d%% - wind: %-2s %14s\n" \
        "$name" "$(date --date="$day" +'%-d %b')" \
        "$temp" "$tempunit" \
        "$probprecip" \
        "$winddir" "$windsp"
    fi

#    printf "    %s\n    %s\n" "$shfcst" "$lnfcst"
  }
}

getwx_hourly()
{
  echo "getwx_hourly()" >&3
  local fcsturl=$(jq -r '.properties.forecastHourly' <<<"$wx_point_data")
  echo "getwx_hourly() fcsturl: $fcsturl" >&3
  local fcstdata=$(curl -sfLG "$fcsturl" | jq .)
  echo "getwx_hourly() fcstdata bytes: ${#fcstdata}" >&3
  zonename=$(jq -r '.properties.name' < <(curl -sfLG "$(jq -r '.properties.forecastZone' <<<"$wx_point_data")"))
}

getwx_temp()
{
  local stnsurl=$(jq -r '.properties.observationStations' <<<"$wx_point_data")
  echo "getwx_temp($1) stnsurl: $stnsurl" >&3
  local wxdata2=$(curl -sfLG "$stnsurl" )
  echo "getwx_temp($1): wxdata2: ${#wxdata2} bytes" >&3
  local obsvurl=$(jq -r '.features[0].id' <<<"$wxdata2")/observations/latest
  echo "getwx_temp($1): obsvurl: $obsvurl" >&3
  local obsv=$(curl -sfLG "$obsvurl" | jq .properties)

  local temperature
  temperature=$(temptoF $(jq -cr '.temperature' <<<"$obsv"))

  echo "$temperature"
}

getwx_point_data "$wx_location"
if [ "$wx_point_data" = "" ] ; then
  echo "Invalid location: $wx_location" >&2
  exit 1
fi

if [ $wx_do_conditions -ne 0 ] ; then getwx_conditions ; fi
if [ $wx_do_forecast   -ne 0 ] ; then getwx_forecast   ; fi
if [ $wx_do_hourly     -ne 0 ] ; then getwx_hourly     ; fi
if [ $wx_do_temp       -ne 0 ] ; then getwx_temp       ; fi

